# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
 
jobs:
  this_job_should_fail:
    docker: 
      - image: circleci/node:13.8.0
    steps:
      - run: 
          command: exit 1
      - run:
          name: on error
          command: echo "this job has failed (non-zero exit code)"
          when: on_fail


# Orchestrate or schedule a set of jobs
workflows:
  just-do-it:
    jobs:
      - this_job_should_fail