# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  print-hello:
    docker: 
      - image: circleci/node:13.8.0
    steps:
      - run: echo "hello"
  print-world:
    docker: 
      - image: circleci/node:13.8.0
    steps:
      - run: echo "world"
# Orchestrate or schedule a set of jobs
workflows:
  # Name the workflow "welcome"
  print-hello-world:
    # Run the welcome/run job in its own container
    jobs:
      - print-hello
      - print-world:
          requires: 
          - print-hello
